#!/bin/bash

#
# 98-noint-liferay
#

# Functions

## Helpers
_notify_task() {
    local title=$1
    local message=$2
    if command -v notify > /dev/null 2>&1; then
        notify "$title" "$message"
    else
        echo "$title" "-" "$message"
    fi
}

## commands
baseline() {
    blade gw baseline "$@"

    local build_exit_code=$?
    if [ $build_exit_code -ne 0 ]; then
        _notify_task "Baseline" "Failed."
    else
        _notify_task "Baseline" "Completed!"
    fi

    return $build_exit_code
}

deploy() {
    blade gw deploy "$@";

    local build_exit_code=$?
    if [ $build_exit_code -ne 0 ]; then
        _notify_task "Deploy" "Failed."
    else
        _notify_task "Deploy" "Completed!"
    fi

    return $build_exit_code
}

deploya() {
   deploy -a -Pnodejs.node.env=development "$@";
}

dropdb() {
    if [[ -n "$1" ]]; then
        sudo -u postgres psql -c "drop database $1 with (force);"
    else
        sudo -u postgres psql -c 'drop database lportal with (force);'
    fi
}

recreatedb() {
    if [[ -n "$1" ]]; then
        dropdb "$1" && sudo -u postgres psql -c "create database $1 owner sa;"
    else
        dropdb && sudo -u postgres psql -c 'create database lportal owner sa;'
    fi
}

sf() {
    blade gw formatSource "$@"

    local build_exit_code=$?
    if [ $build_exit_code -ne 0 ]; then
        _notify_task "FormatSource" "Failed."
    else
        _notify_task "FormatSource" "Completed!"
    fi

    return $build_exit_code
}

sfc() {
    if [[ -n "$LIFERAY_PRJ" ]]; then
        (
            cd "$LIFERAY_PRJ/portal-impl";
            ant format-source-current-branch;
        )

        local ant_exit_code=$?

        if [ $ant_exit_code -ne 0 ]; then
            _notify_task "Ant format-source-current-branch" "Build failed."
        else
            _notify_task "Ant format-source-current-branch" "Build completed!"
        fi

        return $ant_exit_code
    else
        _notify_task "Ant format-source-current-branch Failed" "You need to populate the env variable LIFERAY_PRJ"
        return 1
    fi
}

sfl() {
    if [[ -n "$LIFERAY_PRJ" ]]; then
        (
            cd "$LIFERAY_PRJ/portal-impl";
            ant format-source-local-changes;
        )

        local ant_exit_code=$?

        if [ $ant_exit_code -ne 0 ]; then
            _notify_task "Ant format-source-local-changes" "Build failed."
        else
            _notify_task "Ant format-source-local-changes" "Build completed!"
        fi

        return $ant_exit_code
    else
        _notify_task "Ant format-source-local-changes Failed" "You need to populate the env variable LIFERAY_PRJ"
        return 1
    fi
}

build-portal-service() {
    local status=0
    if [[ -n "$LIFERAY_PRJ" ]]; then
        (
            cd $LIFERAY_PRJ/portal-impl
            ant build-service-portal build-service-portlets
        )

        local build_exit_code=$?
        if [ $build_exit_code -ne 0 ]; then
            _notify_task "Build portal service" "Failed."
        else
            _notify_task "Build portal service" "Completed!"
        fi
        return $build_exit_code
    else
        _notify_task "Build portal service" "You need to populate the env variable LIFERAY_PRJ"
        return 1
    fi
}

build-rest() {
    blade gw buildRest "$@"

    local build_exit_code=$?
    if [ $build_exit_code -ne 0 ]; then
        _notify_task "BuildRest" "Failed."
    else
        _notify_task "BuildRest" "Completed!"
    fi

    return $build_exit_code
}

build-service() {
    blade gw buildService "$@"

    local build_exit_code=$?
    if [ $build_exit_code -ne 0 ]; then
        _notify_task "BuildService" "Failed."
    else
        _notify_task "BuildService" "Completed!"
    fi

    return $build_exit_code
}

build-language() {
    local status=0
    if [[ -n "$LIFERAY_PRJ" ]]; then
        (
            cd $LIFERAY_PRJ/modules/apps/portal-language;
            blade gw buildLang "$@"
        )

        local build_exit_code=$?
        if [ $build_exit_code -ne 0 ]; then
            _notify_task "BuildLanguage" "Failed."
        else
            _notify_task "BuildLanguage" "Completed!"
        fi
        return $build_exit_code
    else
        _notify_task "BuildLanguage" "You need to populate the env variable LIFERAY_PRJ"
        return 1
    fi
}

rebuild() {
    local status=0
    if [[ -n "$LIFERAY_PRJ" ]]; then
        (
            cd $LIFERAY_PRJ;
            ant setup-sdk && ant setup-profile-dxp && ij && ant all && ij
        )

        local ant_exit_code=$?

        if [ $ant_exit_code -ne 0 ]; then
            _notify_task "Ant all" "Build failed."
        else
            _notify_task "Ant all" "Build completed!"
        fi

        return $ant_exit_code
    else
        _notify_task "Ant all Failed" "You need to populate the env variable LIFERAY_PRJ"
        return 1
    fi
}

rebuild-full() {
    if [[ -n "$LIFERAY_PRJ" ]]; then
        (
            cd $LIFERAY_PRJ &&
            git clean -dfx -e "build.$(whoami).properties" -e "app.server.$(whoami).properties" &&
            ant setup-sdk && ant setup-profile-dxp && ij && ant all && ij
        )

        local ant_exit_code=$?

        if [ $ant_exit_code -ne 0 ]; then
            _notify_task "Ant all" "Build failed."
        else
            _notify_task "Ant all" "Build completed!"
        fi

        return $ant_exit_code
    else
        _notify_task "Ant all Failed" "You need to populate the env variable LIFERAY_PRJ"
        return 1
    fi
}

testIntegration() {
   blade gw testIntegration "$@"
}

tomclear() {
    if [[ -z "$LIFERAY_HOME" ]]; then
        _notify_task "Clear tomcat failed" "You need to populate the env variable LIFERAY_HOME"
        return 1;
    fi

    local folders_to_empty=(
        "osgi/state"
        "tomcat/work"
        "tomcat/temp"
    )

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dir)
                if [[ -n "$2" && "$2" != --* ]]; then
                    folders_to_empty+=("$2")
                    shift 2 # Sposta la coda degli argomenti di due posizioni
                else
                    echo "Error: --dir requires a value."
                    return 1
                fi
                ;;
            *)
                echo "Unknows parameter: $1"
                shift
                ;;
        esac
    done

    for folder in "${folders_to_empty[@]}"; do
        local full_path="${LIFERAY_HOME}/${folder}"

        if [ -d "$full_path" ]; then
            if [ "$(ls -A "$full_path" 2>/dev/null)" ]; then
                echo "Emptying directory $full_path."
                rm -rf "$full_path"/*
            else
                echo "Directory $full_path is empty already."
            fi
        else
            echo "Directory $full_path does not exist. Skipping."
        fi
    done
}


tomclearfull() {
    tomclear --dir "data"
}

tominit() {
    tomstop;
    tomclearfull && recreatedb && tomstart
}

tomlog() {
    if [[ -z "$LIFERAY_HOME" ]]; then
        echo  "Error: You need to populate the env variable LIFERAY_HOME."
        return 1
    fi
    if [[ -z "$PAGER" ]]; then
        echo "Error: you need to define a pager in your PAGER env variable."
        return 1
    fi

    local tomcat_log="$LIFERAY_HOME/tomcat/logs/catalina.out"
    $PAGER "$tomcat_log";
}

tomrestart() {
    tomstop;
    tomclear && tomstart
}

tomstart() {
    if [[ -n "$LIFERAY_HOME" ]]; then
        local tomcat_log="$LIFERAY_HOME/tomcat/logs/catalina.out"
        rm -rf "$tomcat_log" &&
        "$LIFERAY_HOME/tomcat/bin/catalina.sh" glowroot jpda start && if [[ -n "$PAGER" ]]; then $PAGER "$tomcat_log";fi
    else
        _notify_task "Start failed" "You need to populate the env variable LIFERAY_HOME"
        return 1
    fi
}

tomstop() {
    if [[ -n "$LIFERAY_HOME" ]]; then
        "$LIFERAY_HOME/tomcat/bin/catalina.sh" stop
    else
        _notify_task "Start failed" "You need to populate the env variable LIFERAY_HOME"
        return 1
    fi
}
